### ISSUE TITLE
Act_7 Línea de tiempo "La web 1.0, 2.0 y 3.0"

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-7-Daisy-GonzalezLita12#1]
Act_7 Línea de tiempo "La web 1.0, 2.0 y 3.0"
Alumna:Daisy Gonzalez lita
Grupo: 1BS
[linea_web.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-Daisy-GonzalezLita12/files/9783011/linea_web.pdf)

**Comment by ErikCuevas03** [comment]
Calificación 20, bien hecho

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
